<a href="https://colab.research.google.com/github/Ekene-Ebenezer/Gomycode-Data-Science/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ydata Profiling

Checkpoint Objective

In this checkpoint, we are going to work on 'Education Attainment And Enrolment Around The World' dataset, provided by the World bank group.

Dataset description : The dataset was derived from the original copy, which was published on the world bank website. The primary purpose of this database is to document and analyse patterns of educational attainment rates in different country around the world.

[Datalink](https://drive.google.com/file/d/1v4qPmCg2AGHgUmpc-n4J5e2M8zur7t5N/view?usp=sharing)

Columns description :


>Age[15-49]All_gradeX : Percentage of the entire population ages 15 to 49 that has completed grade X

>Age[15-49]Male_gradeX : Percentage of the male population ages 15 to 49 that has completed grade X

>Age[15-49]Female_gradeX : Percentage of the female population ages 15 to 49 that has completed grade X
X = [1...3]

Instructions

Step 1: Data exploration with Pandas
Download the provided dataset
Use pandas to read the file into a pandas Dataframe.
Display general information about the dataset.
Run descriptive analysis on the dataset using the 'describe' function.

Step 2: Data exploration with ydata-profiling
Use ydata-profiling to generate a report of the provided dataset.
Look for missing values in the dataset. You can use the report generated by ydata to identify missing values.
Examine the correlations between different columns in the dataset. You can use the report generated by ydata to identify correlations.
Identify any other interesting patterns or insights in the dataset that you can discover through the ydata-profiling report.

Step 3: Summary
Write a summary of your findings based on the ydata-profiling report. Be sure to include any interesting patterns or insights you discovered in the dataset.

In [ ]:
#install Ydata Profiling
!pip install pandas-profiling

Collecting pandas-profiling
  Downloading pandas_profiling-3.6.6-py2.py3-none-any.whl (324 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 5.1 MB/s eta 0:00:00
Collecting ydata-profiling (from pandas-profiling)
  Downloading ydata_profiling-4.6.4-py2.py3-none-any.whl (357 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 357.8/357.8 kB 27.3 MB/s eta 0:00:00
Requirement already satisfied: scipy<1.12,>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.11.4)
Requirement already satisfied: pandas!=1.4.0,<3,>1.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib<3.9,>=3.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (3.7.1)
Collecting pydantic>=2 (from ydata-profiling->pandas-profiling)
  Downloading pydantic-2.5.3-py3-none-any.whl (381 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.9/381.9 kB 33.4 MB/s eta 0:00:00
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (6.0.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (3.1.2)
Collecting visions[type_image_path]==0.7.5 (from ydata-profiling->pandas-profiling)
  Downloading visions-0.7.5-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.7/102.7 kB 11.2 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.26,>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.23.5)
Collecting htmlmin==0.1.12 (from ydata-profiling->pandas-profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata-profiling->pandas-profiling)
  Downloading phik-0.12.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (686 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 686.1/686.1 kB 47.8 MB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (2.31.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (4.66.1)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.12.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling->pandas-profiling)
  Downloading multimethod-1.10-py3-none-any.whl (9.9 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.14.1)
Collecting typeguard<5,>=4.1.2 (from ydata-profiling->pandas-profiling)
  Downloading typeguard-4.1.5-py3-none-any.whl (34 kB)
Collecting imagehash==4.3.1 (from ydata-profiling->pandas-profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 26.5 MB/s eta 0:00:00
Requirement already satisfied: wordcloud>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.9.3)
Collecting dacite>=1.8 (from ydata-profiling->pandas-profiling)
  Downloading dacite-1.8.1-py3-none-any.whl (14 kB)
Requirement already satisfied: numba<0.59.0,>=0.56.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.58.1)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (1.5.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (9.4.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (23.2.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (3.2.1)
Collecting tangled-up-in-unicode>=0.0.4 (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling)
  Downloading tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 77.5 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.2->ydata-profiling->pandas-profiling) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.2->ydata-profiling->pandas-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.2->ydata-profiling->pandas-profiling) (4.47.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.2->ydata-profiling->pandas-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.2->ydata-profiling->pandas-profiling) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.2->ydata-profiling->pandas-profiling) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<3.9,>=3.2->ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba<0.59.0,>=0.56.0->ydata-profiling->pandas-profiling) (0.41.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.4.0,<3,>1.1->ydata-profiling->pandas-profiling) (2023.3.post1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-profiling) (1.3.2)
Collecting annotated-types>=0.4.0 (from pydantic>=2->ydata-profiling->pandas-profiling)
  Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting pydantic-core==2.14.6 (from pydantic>=2->ydata-profiling->pandas-profiling)
  Downloading pydantic_core-2.14.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 41.2 MB/s eta 0:00:00
Collecting typing-extensions>=4.6.1 (from pydantic>=2->ydata-profiling->pandas-profiling)
  Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2023.11.17)
Requirement already satisfied: patsy>=0.5.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (0.5.6)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.4->statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (1.16.0)
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=6bcbf1277312d9e3d63ed282dceda6b142654a70e56dcedfcac1934153ad75b8
  Stored in directory: /root/.cache/pip/wheels/dd/91/29/a79cecb328d01739e64017b6fb9a1ab9d8cb1853098ec5966d
Successfully built htmlmin
Installing collected packages: htmlmin, typing-extensions, tangled-up-in-unicode, multimethod, dacite, annotated-types, typeguard, pydantic-core, imagehash, visions, pydantic, phik, ydata-profiling, pandas-profiling
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.5.0
    Uninstalling typing_extensions-4.5.0:
      Successfully uninstalled typing_extensions-4.5.0
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.13
    Uninstalling pydantic-1.10.13:
      Successfully uninstalled pydantic-1.10.13
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires openai, which is not installed.
llmx 0.0.15a0 requires tiktoken, which is not installed.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.9.0 which is incompatible.
Successfully installed annotated-types-0.6.0 dacite-1.8.1 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.10 pandas-profiling-3.6.6 phik-0.12.4 pydantic-2.5.3 pydantic-core-2.14.6 tangled-up-in-unicode-0.2.0 typeguard-4.1.5 typing-extensions-4.9.0 visions-0.7.5 ydata-profiling-4.6.4

In [1]:
import pandas as pd

In [2]:
#importing dataset

EDUCATION_Dataset = pd.read_csv("/content/EDUCATION_ATTAINMENT.csv")

In [3]:
#basic information about the dataset

EDUCATION_Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 38 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Ages[15-49]_All_grade1     626 non-null    float64
 1   Ages[15-49]_All_grade2     626 non-null    float64
 2   Ages[15-49]_All_grade3     626 non-null    float64
 3   Ages[20-29]_All_grade1     626 non-null    float64
 4   Ages[20-29]_All_grade2     626 non-null    float64
 5   Ages[20-29]_All_grade3     626 non-null    float64
 6   Ages[30-39]_All_grade1     625 non-null    float64
 7   Ages[30-39]_All_grade2     625 non-null    float64
 8   Ages[30-39]_All_grade3     625 non-null    float64
 9   Ages[40-49]_All_grade1     625 non-null    float64
 10  Ages[40-49]_All_grade2     625 non-null    float64
 11  Ages[40-49]_All_grade3     625 non-null    float64
 12  Ages[15-49]_Male_grade1    626 non-null    float64
 13  Ages[15-49]_Male_grade2    626 non-null    float64
 14  Ages[15-49]_Male_grade3    626 non-null    float64
 15  Ages[20-29]_Male_grade1    626 non-null    float64
 16  Ages[20-29]_Male_grade2    626 non-null    float64
 17  Ages[20-29]_Male_grade3    626 non-null    float64
 18  Ages[30-39]_Male_grade1    625 non-null    float64
 19  Ages[30-39]_Male_grade2    625 non-null    float64
 20  Ages[30-39]_Male_grade3    625 non-null    float64
 21  Ages[40-49]_Male_grade1    625 non-null    float64
 22  Ages[40-49]_Male_grade2    625 non-null    float64
 23  Ages[40-49]_Male_grade3    625 non-null    float64
 24  Ages[15-49]_Female_grade1  626 non-null    float64
 25  Ages[15-49]_Female_grade2  626 non-null    float64
 26  Ages[15-49]_Female_grade3  626 non-null    float64
 27  Ages[20-29]_Female_grade1  626 non-null    float64
 28  Ages[20-29]_Female_grade2  626 non-null    float64
 29  Ages[20-29]_Female_grade3  626 non-null    float64
 30  Ages[30-39]_Female_grade1  625 non-null    float64
 31  Ages[30-39]_Female_grade2  625 non-null    float64
 32  Ages[30-39]_Female_grade3  625 non-null    float64
 33  Ages[40-49]_Female_grade1  625 non-null    float64
 34  Ages[40-49]_Female_grade2  625 non-null    float64
 35  Ages[40-49]_Female_grade3  625 non-null    float64
 36  country                    626 non-null    object
 37  year                       626 non-null    int64
dtypes: float64(36), int64(1), object(1)
memory usage: 186.0+ KB

In [4]:
#overview of dataset

EDUCATION_Dataset.head(15)

,Ages[15-49]_All_grade1,Ages[15-49]_All_grade2,Ages[15-49]_All_grade3,Ages[20-29]_All_grade1,Ages[20-29]_All_grade2,Ages[20-29]_All_grade3,Ages[30-39]_All_grade1,Ages[30-39]_All_grade2,Ages[30-39]_All_grade3,Ages[40-49]_All_grade1,...,Ages[20-29]_Female_grade2,Ages[20-29]_Female_grade3,Ages[30-39]_Female_grade1,Ages[30-39]_Female_grade2,Ages[30-39]_Female_grade3,Ages[40-49]_Female_grade1,Ages[40-49]_Female_grade2,Ages[40-49]_Female_grade3,country,year
0,0.669091,0.667214,0.651812,0.460899,0.458749,0.446925,0.292791,0.290929,0.279100,0.250981,...,0.279915,0.272185,0.111428,0.109101,0.103791,0.098721,0.097825,0.092263,Afghanistan,2015
1,0.485879,0.480171,0.465510,0.267236,0.265735,0.257999,0.191279,0.188839,0.182693,0.187151,...,0.122435,0.117916,0.084555,0.083607,0.080518,0.065466,0.065466,0.064012,Afghanistan,2007
2,0.516431,0.514233,0.502269,0.327775,0.326250,0.318003,0.221981,0.220472,0.214040,0.205611,...,0.157744,0.151130,0.086072,0.085138,0.082124,0.073085,0.073037,0.071735,Afghanistan,2010
3,0.914294,0.903528,0.871690,0.853770,0.840792,0.810794,0.775725,0.757109,0.713569,0.786468,...,0.786506,0.746073,0.699617,0.675786,0.618058,0.687626,0.648913,0.576818,Angola,2015
4,0.876990,0.841497,0.762864,0.881265,0.854158,0.795892,0.883625,0.853812,0.805231,0.747516,...,0.793379,0.712726,0.808248,0.762858,0.693267,0.559192,0.516735,0.429649,Angola,1999
5,0.889589,0.852069,0.771968,0.831665,0.794070,0.734560,0.784236,0.737433,0.667450,0.766246,...,0.707985,0.633392,0.695446,0.630993,0.541367,0.623666,0.545770,0.464623,Angola,2008
6,0.803733,0.746789,0.631720,0.750124,0.720764,0.654041,0.765275,0.737825,0.675347,0.637211,...,0.624397,0.546101,0.649015,0.607746,0.525118,0.410228,0.366791,0.317850,Angola,2001
7,0.981062,0.981062,0.980476,0.982854,0.982854,0.980559,0.984600,0.984600,0.984600,0.984417,...,0.987454,0.986111,0.990672,0.990672,0.990672,0.978536,0.978536,0.978536,Albania,2002
8,0.991079,0.985556,0.981743,0.984294,0.980344,0.977792,0.976801,0.971111,0.969247,0.989354,...,0.976583,0.972163,0.974779,0.968926,0.967719,0.987297,0.982982,0.982982,Albania,2017
9,0.992481,0.990077,0.984427,0.994806,0.994806,0.993977,0.994772,0.994567,0.991585,0.993558,...,1.000000,0.999269,0.998587,0.998186,0.995178,1.000000,0.996559,0.989040,Albania,2000
10,0.992832,0.992452,0.991886,0.987458,0.987458,0.987458,0.992291,0.992291,0.992291,0.994939,...,0.984984,0.984984,0.991482,0.991482,0.991482,0.995492,0.995492,0.994883,Albania,2005
11,0.997315,0.996852,0.996852,0.997692,0.997692,0.997028,0.996044,0.995730,0.995566,0.996964,...,0.998409,0.997744,0.996425,0.995833,0.995833,0.996803,0.996166,0.996166,Armenia,2000
12,0.993256,0.992704,0.992335,0.997937,0.997311,0.996383,0.997257,0.997257,0.997257,0.999479,...,0.997916,0.996376,0.997660,0.997660,0.997660,0.999220,0.998578,0.997699,Armenia,2005
13,0.995814,0.995814,0.995814,0.996189,0.995662,0.995662,0.997282,0.997282,0.997282,0.998603,...,0.997077,0.997077,0.995618,0.995618,0.995618,0.999227,0.999227,0.999073,Armenia,2010
14,0.997350,0.997350,0.997350,0.998235,0.998235,0.997007,0.997835,0.997637,0.997184,0.997800,...,0.998500,0.998500,0.999209,0.999209,0.998457,0.996951,0.996951,0.996951,Armenia,2015

In [5]:
#Descriptive statistics of the dataset

EDUCATION_Dataset.describe()

,Ages[15-49]_All_grade1,Ages[15-49]_All_grade2,Ages[15-49]_All_grade3,Ages[20-29]_All_grade1,Ages[20-29]_All_grade2,Ages[20-29]_All_grade3,Ages[30-39]_All_grade1,Ages[30-39]_All_grade2,Ages[30-39]_All_grade3,Ages[40-49]_All_grade1,...,Ages[20-29]_Female_grade1,Ages[20-29]_Female_grade2,Ages[20-29]_Female_grade3,Ages[30-39]_Female_grade1,Ages[30-39]_Female_grade2,Ages[30-39]_Female_grade3,Ages[40-49]_Female_grade1,Ages[40-49]_Female_grade2,Ages[40-49]_Female_grade3,year
count,626.000000,626.000000,626.000000,626.000000,626.000000,626.000000,625.000000,625.000000,625.000000,625.000000,...,626.000000,626.000000,626.000000,625.000000,625.000000,625.000000,625.000000,625.000000,625.000000,626.000000
mean,0.873886,0.861490,0.837509,0.823849,0.812738,0.789965,0.766171,0.752519,0.724980,0.709166,...,0.790544,0.778972,0.755644,0.719020,0.704342,0.675526,0.646864,0.628309,0.593585,2005.049521
std,0.162624,0.166895,0.176555,0.200559,0.202587,0.207979,0.236563,0.237679,0.240681,0.259998,...,0.236541,0.238637,0.243755,0.278133,0.279059,0.281139,0.302723,0.302637,0.301434,7.894248
min,0.251917,0.244071,0.233274,0.079610,0.079610,0.079610,0.098059,0.091358,0.085236,0.036549,...,0.029662,0.029662,0.029662,0.060930,0.058368,0.053241,0.022547,0.022022,0.020972,1981.000000
25%,0.831791,0.803131,0.757465,0.744915,0.723418,0.678869,0.639447,0.612464,0.561545,0.527055,...,0.678596,0.658977,0.616380,0.534060,0.508218,0.463656,0.400638,0.372404,0.330846,2000.000000
50%,0.948926,0.935167,0.909587,0.910132,0.896568,0.864849,0.853861,0.831246,0.794898,0.785356,...,0.900869,0.887206,0.853414,0.815823,0.794049,0.749927,0.719924,0.686513,0.625602,2005.000000
75%,0.984447,0.980112,0.971166,0.973777,0.967410,0.955625,0.959097,0.948259,0.922841,0.937129,...,0.974514,0.968962,0.959495,0.958022,0.946510,0.920707,0.929507,0.914777,0.875928,2011.000000
max,1.000000,1.000000,1.000000,1.000000,0.999824,0.999264,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,0.999777,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2020.000000

# - Data Exploration with Ydata

In [6]:
# Import the Ydata_profiling library that have been installed
import ydata_profiling as ydp

# Imports profile for creating html or notebook from ydata_profiling results
import profile

#Generates the report
from ydata_profiling import ProfileReport

ModuleNotFoundError: No module named 'ydata_profiling'

In [7]:
#Creates a Ydata profile with the Title "Education Attainment Profile"

Education_DataProfile = ProfileReport(EDUCATION_Dataset, title = " Education Attainment Profile", minimal = True)

NameError: name 'ProfileReport' is not defined

In [ ]:
#Generates the profile

Education_DataProfile

This cell output is too large and can only be displayed while logged in.

In [ ]:
#using grouo by function. This is not part of the code
EDUCATION_Dataset.groupby(["country", "year"]).mean()

                  Ages[15-49]_All_grade1  Ages[15-49]_All_grade2  \
country     year
Afghanistan 2007                0.485879                0.480171
            2010                0.516431                0.514233
            2015                0.669091                0.667214
Albania     2000                0.992481                0.990077
            2002                0.981062                0.981062
...                                  ...                     ...
Zimbabwe    2009                0.993604                0.989401
            2010                0.987620                0.985260
            2014                0.994425                0.992300
            2015                0.994478                0.990348
            2019                0.993671                0.991859

                  Ages[15-49]_All_grade3  Ages[20-29]_All_grade1  \
country     year
Afghanistan 2007                0.465510                0.267236
            2010                0.502269                0.327775
            2015                0.651812                0.460899
Albania     2000                0.984427                0.994806
            2002                0.980476                0.982854
...                                  ...                     ...
Zimbabwe    2009                0.983428                0.987763
            2010                0.978837                0.988720
            2014                0.987499                0.991362
            2015                0.986915                0.991449
            2019                0.985111                0.993362

                  Ages[20-29]_All_grade2  Ages[20-29]_All_grade3  \
country     year
Afghanistan 2007                0.265735                0.257999
            2010                0.326250                0.318003
            2015                0.458749                0.446925
Albania     2000                0.994806                0.993977
            2002                0.982854                0.980559
...                                  ...                     ...
Zimbabwe    2009                0.984321                0.977343
            2010                0.986780                0.981525
            2014                0.989737                0.985291
            2015                0.989851                0.984804
            2019                0.988796                0.983957

                  Ages[30-39]_All_grade1  Ages[30-39]_All_grade2  \
country     year
Afghanistan 2007                0.191279                0.188839
            2010                0.221981                0.220472
            2015                0.292791                0.290929
Albania     2000                0.994772                0.994567
            2002                0.984600                0.984600
...                                  ...                     ...
Zimbabwe    2009                0.983226                0.980478
            2010                0.977844                0.974075
            2014                0.984826                0.982728
            2015                0.987105                0.985023
            2019                0.990576                0.986393

                  Ages[30-39]_All_grade3  Ages[40-49]_All_grade1  ...  \
country     year                                                  ...
Afghanistan 2007                0.182693                0.187151  ...
            2010                0.214040                0.205611  ...
            2015                0.279100                0.250981  ...
Albania     2000                0.991585                0.993558  ...
            2002                0.984600                0.984417  ...
...                                  ...                     ...  ...
Zimbabwe    2009                0.973111                0.911083  ...
            2010                0.967946                0.932959  ...
            2014                0.975637                0.967994  ...
            2015                0.979358                0.970577  ...
            2019                0.976674                0.981112  ...

                  Ages[15-49]_Female_grade3  Ages[20-29]_Female_grade1  \
country     year
Afghanistan 2007                   0.318244                   0.123089
            2010                   0.353592                   0.159424
            2015                   0.493414                   0.281518
Albania     2000                   0.991679                   1.000000
            2002                   0.983639                   0.987454
...                                     ...                        ...
Zimbabwe    2009                   0.986621                   0.985880
            2010                   0.980983                   0.987740
            2014                   0.990722                   0.990629
            2015                   0.988584                   0.988781
            2019                   0.988005                   0.992494

                  Ages[20-29]_Female_grade2  Ages[20-29]_Female_grade3  \
country     year
Afghanistan 2007                   0.122435                   0.117916
            2010                   0.157744                   0.151130
            2015                   0.279915                   0.272185
Albania     2000                   1.000000                   0.999269
            2002                   0.987454                   0.986111
...                                     ...                        ...
Zimbabwe    2009                   0.981323                   0.976010
            2010                   0.985412                   0.979868
            2014                   0.989167                   0.986087
            2015                   0.988470                   0.984984
            2019                   0.989465                   0.984687

                  Ages[30-39]_Female_grade1  Ages[30-39]_Female_grade2  \
country     year
Afghanistan 2007                   0.084555                   0.083607
            2010                   0.086072                   0.085138
            2015                   0.111428                   0.109101
Albania     2000                   0.998587                   0.998186
            2002                   0.990672                   0.990672
...                                     ...                        ...
Zimbabwe    2009                   0.977775                   0.974418
            2010                   0.970045                   0.965159
            2014                   0.980323                   0.977985
            2015                   0.979650                   0.977850
            2019                   0.988121                   0.982323

                  Ages[30-39]_Female_grade3  Ages[40-49]_Female_grade1  \
country     year
Afghanistan 2007                   0.080518                   0.065466
            2010                   0.082124                   0.073085
            2015                   0.103791                   0.098721
Albania     2000                   0.995178                   1.000000
            2002                   0.990672                   0.978536
...                                     ...                        ...
Zimbabwe    2009                   0.963542                   0.869159
            2010                   0.955577                   0.895031
            2014                   0.970721                   0.949987
            2015                   0.971157                   0.956777
            2019                   0.972860                   0.973609

                  Ages[40-49]_Female_grade2  Ages[40-49]_Female_grade3
country     year
Afghanistan 2007                   0.065466                   0.064012
            2010                   0.073037                   0.071735
            2015                   0.097825                   0.092263
Albania     2000                   0.996559                   0.989040
            2002                   0.978536                   0.978536
...                                     ...                        ...
Zimbabwe    2009                   0.855555                   0.821532
            2010                   0.884101                   0.857503
            2014                   0.940304                   0.925455
            2015                   0.950906                   0.936746
            2019                   0.968685                   0.955590

[590 rows x 36 columns]

In [ ]:
#Converts the profile created into a html file
Education_DataProfile.to_file("Edu_DataProfile")

/usr/local/lib/python3.10/dist-packages/ydata_profiling/profile_report.py:354: UserWarning: Try running command: 'pip install --upgrade Pillow' to avoid ValueError
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/ydata_profiling/profile_report.py:375: UserWarning: Extension  not supported. For now we assume .html was intended. To remove this warning, please use .html or .json.
  warnings.warn(

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# Summary of the Dataset Profiling

Based on the result from the Ydata Profiling;

> There are a total of 18 missing value among the 626 observations which comprises of 0.1 of the overall dataset.

> The dataset contains 129 distinct couuntries and years raning 1981 to 2020

In [ ]:
#Converts the profile created into a notebook

Education_DataProfile.to_notebook_iframe()

This cell output is too large and can only be displayed while logged in.